import React from 'react'




export const occupationOptions=[
    [   
        'Administration',
        'Agriculturist',
        'Analyst',
        'Arborist',
        'Computer Operator',
        'Consultant',
        'Day Labourer',
        'Driver/Delivery person',
        'Farmer',
        'Fisherman',
        'Inspector',
        'Logger',
        'Machine Operator',
        'Manager/Supervisor',
        'Maritime Pilot',
        'Miner',
        'Office Worker',
        'Other - Specify',
        'Project Manager',
        'Seaman',
        'Senior Management',
        'Ship Captain',
        'Steelworker',
        'Technician/Professional',
        'Trapper/Hunter',
    ],
    [
        'Administration',
        'Analyst',
        'Baker/Pastry Cook',
        'Bartender',
        'Bellboy/Porter',
        'Butcher',
        'Chef',
        'Consultant',
        'Cook/Kitchen Staff',
        'Delivery Person',
        'Employee - Fast-Food Industry',
        'Engineer',
        'Food Producer',
        'Hotel Employee',
        'Manager/Supervisor',
        'Office Worker',
        'Other - Specify',
        'Project Manager',
        'Senior Management',
        'Technician/Professional',
        'Waiter',
    ],
    [
        'Administration',
        'Analyst',
        'Artist',
        'Audio Engineer',
        'Comedian/Actor',
        'Consultant',
        'Dancer',
        'Designer/Scenic Artist',
        'Director',
        'Floor Director',
        'Light/Sound Technician',
        'Manager/Supervisor',
        'Museum Employee',
        'Musician',
        'Musician/Singer',
        'Office Worker',
        'Orchestra Conductor',
        'Other - Specify',
        'Performer',
        'Photographer',
        'Playwright',
        'Producer',
        'Professional Athlete',
        'Professional Coach',
        'Project Manager',
        'Publisher',
        'Sculptor',
        'Senior Management',
        'Singer',
        'Stagehand',
        'Tattoo Artist',
        'Technician/Professional',
    ],

] 