import React from 'react'




export const occupationOptions=[
    // 1
    [   
        'Administration',
        'Agriculturist',
        'Analyst',
        'Arborist',
        'Computer Operator',
        'Consultant',
        'Day Labourer',
        'Driver/Delivery person',
        'Farmer',
        'Fisherman',
        'Inspector',
        'Logger',
        'Machine Operator',
        'Manager/Supervisor',
        'Maritime Pilot',
        'Miner',
        'Office Worker',
        'Other - Specify',
        'Project Manager',
        'Seaman',
        'Senior Management',
        'Ship Captain',
        'Steelworker',
        'Technician/Professional',
        'Trapper/Hunter',
    ],
    // 2
    [
        'Administration',
        'Analyst',
        'Baker/Pastry Cook',
        'Bartender',
        'Bellboy/Porter',
        'Butcher',
        'Chef',
        'Consultant',
        'Cook/Kitchen Staff',
        'Delivery Person',
        'Employee - Fast-Food Industry',
        'Engineer',
        'Food Producer',
        'Hotel Employee',
        'Manager/Supervisor',
        'Office Worker',
        'Other - Specify',
        'Project Manager',
        'Senior Management',
        'Technician/Professional',
        'Waiter',
    ],
    // 3
    [
        'Administration',
        'Analyst',
        'Artist',
        'Audio Engineer',
        'Comedian/Actor',
        'Consultant',
        'Dancer',
        'Designer/Scenic Artist',
        'Director',
        'Floor Director',
        'Light/Sound Technician',
        'Manager/Supervisor',
        'Museum Employee',
        'Musician',
        'Musician/Singer',
        'Office Worker',
        'Orchestra Conductor',
        'Other - Specify',
        'Performer',
        'Photographer',
        'Playwright',
        'Producer',
        'Professional Athlete',
        'Professional Coach',
        'Project Manager',
        'Publisher',
        'Sculptor',
        'Senior Management',
        'Singer',
        'Stagehand',
        'Tattoo Artist',
        'Technician/Professional',
    ],
    // 4
    [
        'Accountant',
        'Accounting Clerk',
        'Actuary',
        'Administration',
        'Analyst',
        'Appraiser',
        'Auditor',
        'Bank Administrator',
        'Call Centre Agent',
        'Chief Financial Officer',
        'Claim Adjuster',
        'Collection Agent/Credit Officer',
        'Compliance Analyst',
        'Consultant',
        'Controller',
        'Counter Representative',
        'Dealer in Securities',
        'Economist',
        'Financial Administration',
        'Financial Analyst',
        'Financial Planner',
        'Fund Manager',
        'Insurance Agent',
        'Investment Analyst',
        'Investment Fund Manager',
        'Investment Professional',
        'Loan Agent',
        'Manager/Supervisor',
        'Mortgage Broker',
        'Mortgage Underwriter',
        'Mutual-Fund Broker',
        'Office Worker',
        'Other - Specify',
        'Risk Specialist',
        'Sales/Service Consultant',
        'Securities Trader',
        'Senior Management',
        'Statistician',
        'Tax Expert',
        'Technician/Professional',
        'Treasury',
    ],
    // 5
    [
        'Artist',
        'Designer',
        'Graphic Artist/Illustration Designer',
        'Graphic Designer',
        'Illustrator',
        'Industrial Designer',
        'Interior Designer',
        'Other - Specify',
        'Photographer/Videographer',
        'Writer',
    ],
    // 6
    [
        'Administration',
        'Air Conditioning Repairman',
        'Analyst',
        'Assembler',
        'Blaster',
        'Boilermaker',
        'Bricklayer/Mason',
        'Cabinetmaker',
        'Carpenter-joiner',
        'Carpenter/Cabinetmaker',
        'Cement Finishing',
        'Consultant',
        'Crane Operator',
        'Diver',
        'Electrician',
        'Elevator Mechanic',
        'Extraction Worker',
        'Fire Protection Mechanic',
        'Flexible Covering Installer',
        'Gardener/Landscaper',
        'General Contractor',
        'Heavy Duty Equipment Mechanic',
        'Heavy Equipment Operator',
        'Industrial Mechanic',
        'Inspector',
        'Insulator',
        'Interior System Installer',
        'Labourer/Helper',
        'Lineworker',
        'Machinist',
        'Manager/Supervisor',
        'Mechanic',
        'Mechanical Fitter (Glazier)',
        'Metal/Plastic Worker',
        'Office Worker',
        'Operator',
        'Other - Specify',
        'Painter',
        'Pipe Welder',
        'Pipefitter',
        'Plasterer',
        'Plumber',
        'Reinforcing Iron Worker',
        'Restorer',
        'Roofer',
        'Senior Management',
        'Specialized Worker',
        'Stripping Shovel Operator',
        'Technician/Professional',
        'Thanatologist',
        'Tile Layer',
        'Welder',
    ],
    // 7
    [
        "Administration",
        "Analyst",
        "Bus Driver",
        "Computer Technician",
        "Consultant",
        "Early Childhood Educator",
        "Educator/Assistant Educator",
        "Historian",
        "Instructor/Trainer",
        "Janitor/Maintenance Employee",
        "Lecturer",
        "Librarian/Archivist",
        "Life Coach",
        "Manager/Supervisor",
        "Office Worker",
        "Orthopedagogist",
        "Other - Specify",
        "Principal/Assistant Principal",
        "Professor",
        "Project Manager",
        "Researcher",
        "School Counsellor",
        "Senior Management",
        "Social Worker",
        "Teacher",
        "Teacher's Assistant",
        "Technician/Professional",
    ],
    // 8
    [
        "Administration",
        "Ambassador/Attaché/Counsellor",
        "Analyst",
        "Armed Forces Officer",
        "Consultant",
        "Dispatcher",
        "Governor/Senate Member",
        "Legislative Assembly Member",
        "Manager/Supervisor",
        "Mayor",
        "Minister/Deputy Minister",
        "Office Worker",
        "Other - Specify",
        "Political Party Leader",
        "Postal Carrier",
        "Public Service",
        "Senior Management",
        "Social Worker",

    ],
    // 9
    [
        "Aerospace Engineer",
        "Architect",
        "Chemical Engineer",
        "Civil Engineer",
        "Consultant",
        "Electrical Engineer",
        "Electrical Network Engineer",
        "Industrial Engineer",
        "Manager",
        "Manufacturing Engineer",
        "Mechanical Engineer",
        "Mining Engineer",
        "Other - Specify",
        "Petroleum Engineer",
        "Professional Engineer",
        "Project Manager",
        "Senior Management - Architecture",
        "Senior Management - Engineering",
        "Software Engineer",
        "Support Activities",        
    ],
    // 10
    [
        "Administration",
        "Analyst",
        "Assembler (Aeronautics)",
        "Consultant",
        "Labourer",
        "Machine Operator",
        "Machinist",
        "Maintenance Employee",
        "Manager/Supervisor",
        "Manufacturing Assembler/Production Worker",
        "Mechanic",
        "Metal/Plastic Worker",
        "Office Worker",
        "Other - Specify",
        "Printer",
        "Senior Management",
        "Sewer",
        "System Assembler",
        "Welder",        
    ],
    // 11
    [
        "Administration",
        "Analyst",
        "Animal Health Technician",
        "Chiropractor",
        "Client Care Attendant",
        "Computer Technician",
        "Consultant",
        "Counselor",
        "Dental Assistant",
        "Dentist",
        "General Practitioner",
        "Health Care Aide",
        "Manager/Supervisor",
        "Medical Specialist",
        "Midwife",
        "Nurse",
        "Nurse Aide",
        "Nutritionist",
        "Occupational therapist",
        "Office Worker",
        "Optometrist",
        "Other - Specify",
        "Pharmacist",
        "Physiotherapist",
        "Project Manager",
        "Psychiatrist",
        "Psychologist",
        "Senior Management",
        "Social Worker",
        "Technician/Professional",
        "Therapist",
        "Veterinarian",
    ],
    // 12
    [
        "Administration",
        "Analyst",
        "Banner Manufacturer",
        "Camera Operator",
        "Consultant",
        "Delivery Driver",
        "Editor",
        "Interpreter",
        "Journalist",
        "Machine Operator",
        "Manager/Supervisor",
        "Office Worker",
        "Other - Specify",
        "Printer",
        "Project Manager",
        "Public Relations",
        "Research Officer",
        "Senior Management",
        "Technician/Professional",
        "Translator",
        "Writer",
    ],
    // 13
    [
        "Missionary/Aid Worker",
        "Occupation related to religion",
        "Other - Specify",
        "Religious Leader",        
    ],
    // 14
    [
        "Articling Law Student",
        "Correctional Officer",
        "Federal Court Justice",
        "Judge",
        "Justice of the Peace",
        "Lawyer",
        "Military Judge",
        "Municipal Judge",
        "Notary",
        "Office Worker",
        "Official Stenographer",
        "Other - Specify",
        "Paralegal",
        "Parole Officer",
        "Probation Officer",
        "Provincial/Territorial Court Justice",
        "Registrar",
        "Security Guard",
        "Supreme Court Judge",       
    ],
    // 15
    [
        "Administration",
        "Border/Customs Officer",
        "Correctional Service Worker",
        "Firefighter/Fire Department Worker",
        "Manager/Supervisor",
        "Office Worker",
        "Other - Specify",
        "Paramedical Staff/Ambulance Attendant",
        "Police Officer",
        "Probation Officer",
        "Safety Guard/Agent",
        "Safety Officer - Air Transport",        
    ],
    // 16
    [
        "Administration",
        "Analyst",
        "Appraiser",
        "Consultant",
        "Manager/Supervisor",
        "Mortgage Broker",
        "Office Worker",
        "Other - Specify",
        "Private House Inspector",
        "Property Manager",
        "Property Valuator",
        "Real Estate Agent",
        "Real Estate Broker",
        "Real Estate Developer",
        "Senior Management",
        "Superintendent/Concierge",
        
    ],
    // 17
    [
        "Administration",
        "Analyst",
        "Consultant",
        "Laboratory Employee",
        "Land Surveyor",
        "Legal Clerk/Secretary",
        "Librarian/Archivist",
        "Manager/Supervisor",
        "Office Worker",
        "Other - Specify",
        "Scientist",
        "Senior Management",
        "Technician/Professional",
        "Translator",        
    ],
    // 18
    [
        "Computer System Analyst",
        "Data Entry Clerk",
        "Electronics Worker",
        "Graphic Designer",
        "Information Technology Specialist",
        "IT Project Director",
        "Manager/Supervisor",
        "Other - Specify",
        "Programmer",
        "Senior Management",
        "Software Engineer",
        "Technical Support",
        "Telecommunications Facility",
        "Telecommunications Specialist",
        "Web Designer",        
    ],
    // 19
    [
        "Administration",
        "Air Traffic Controller",
        "Air Transport Worker",
        "Analyst",
        "Cabin Crew Member",
        "Cabin Maintenance Attendant",
        "Call Centre Agent",
        "Consultant",
        "Delivery Person",
        "Inspector",
        "Limousine Driver",
        "Manager/Supervisor",
        "Material Handler",
        "Motor Vehicle Driver",
        "Office Worker",
        "Other - Specify",
        "Pilot",
        "Rail Industry Worker",
        "Senior Management",
        "Signs and communications Worker",
        "Taxi Driver",
        "Technician/Professional",
        "Ticket Agent",
        "Train Conductor",
        "Truck Driver",
        
    ],
    // 20
    [
        "Administration",
        "Analyst",
        "Animal Groomer",
        "Automotive Services",
        "Barber",
        "Buyer/Supply Officer",
        "Call Centre Support",
        "Car Sales",
        "Cashier",
        "Cleaning Service",
        "Consultant",
        "Cosmetologist",
        "Couturier/Tailor",
        "Craftsperson",
        "Customer Service Representative",
        "Electrologist",
        "Esthetician",
        "Exterminator",
        "Hairdresser",
        "Household Maintenance",
        "Importer/Exporter",
        "Jeweller",
        "Landscaper",
        "Locksmith",
        "Manager/Supervisor",
        "Marketing Representative",
        "Massotherapist",
        "Material Handler/Day Labourer",
        "Merchandiser",
        "Natureopath",
        "Office Worker",
        "Other - Specify",
        "Retailer",
        "Salesperson",
        "Senior Management",
        "Shoe Repairer",
        "Spa/Pool",
        "Telemarketer",
        "Training",
        "Travel Agent",
        "upholsterer",
        "Wholesale Vendor",
        "Window Cleaner",
        
    ],
] 